config/routes.rb
Rails.application.routes.draw do
  resources :uglyterms

  root 'topics#index'

  resources :topics do
  end

  resources :posts do
    member do
      post :reply
    end
  end

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

end

app/models/concerns/publishable.rb
module Concerns
  module Publishable
    extend ActiveSupport::Concern

    included do
      after_create :moderate!

      state_machine :state, :initial => :pending do
        after_transition on: :moderate, do: :queue_on_sidekiq
        event :moderate do
          transition :pending => :moderation
        end

        event :publish do
          transition :moderation => :published
        end
      end
    end

    private

    def queue_on_sidekiq
      ModeratorWorker.perform_async({ class: self.class, id: self.id })
    end
  end
end

app/models/concerns/vocabulary.rb
require 'text'
class Vocabulary
  #TODO: Não seria melhor criar um modelo para manter os termos proibidos?
  BLACKWORDS =  %w(puta gay bicha)

  def initialize
    @clean = []
    @dicionario = {}
    BLACKWORDS.each do |word|
      @dicionario[Text::Metaphone.metaphone(word)] = word
    end
  end

  def expletive?(word)
    return nil if @clean.include? word
    bw = metaphone(word)
    unless bw
      @clean << bw
      return nil
    end
    similarity(word, bw) > 0.50
  end

  private

  def metaphone(word)
    code = Text::Metaphone.metaphone(word)
    return @dicionario[code] if @dicionario.keys.include? code
  end

  def similarity(word, blackword)
    @white ||= Text::WhiteSimilarity.new
    @white.similarity(word, blackword)
  end
end

app/models/concerns/vocabulary_validator.rb
class VocabularyValidator < ActiveModel::Validator
  def validate(record)
    record.errors[:body] << 'Contains strong language' unless sanity? record.body
  end

  private
  def sanity?(text)
    vocabulary = Vocabulary.new

    expletives = text.split(/\W+/).select do |word|
      vocabulary.expletive?(word)
    end
    expletives.empty?
  end
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :string
#  topic_id   :integer
#  created_at :datetime
#  updated_at :datetime
#  state      :string
#

class Post < ActiveRecord::Base
  include Concerns::Publishable

  has_many :post_replies
  has_many :replies, through: :post_replies
  belongs_to :topic

  def reply_to(post_id)
    post = Post.find(post_id)
    post.replies << self
  end

  def replies?
    self.replies.count > 0
  end

  def to_partial_path
    "posts/reply"
  end
end

app/models/post_reply.rb
# == Schema Information
#
# Table name: post_replies
#
#  post_id    :integer
#  reply_id   :integer
#  created_at :datetime
#  updated_at :datetime
#

class PostReply < ActiveRecord::Base
  # Join model class
  belongs_to :post
  belongs_to :reply, class_name: 'Post'

  validates :reply_id, uniqueness: { scope: :post }
end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#  email      :string
#  state      :string
#

class Topic < ActiveRecord::Base
  include Concerns::Publishable

  validates :title, presence: true
  validates :body , presence: true
  validates :email, presence: true

  has_many :posts

  def replies?
    self.replies > 0
  end

  def replies
    self.post.count
  end

  def to_partial_path
    "topics/reply"
  end
end

app/models/uglyterm.rb
# == Schema Information
#
# Table name: uglyterms
#
#  id         :integer          not null, primary key
#  term       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Uglyterm < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @post = Post.create(post_params)
    redirect_to @post.topic
  end

  def reply
    post = Post.find(params[:id])
    reply = Post.new(post_params)
    topic = Topic.find(params[:topic_id])

    if reply.valid?
      post.replies << reply

      redirect_to topic
    else
      flash[:erros] << reply.errors.messages
      redirect_to topic_path(topic)
    end
  end

  private
  def post_params
    params.require(:post).permit(:body, :topic_id)
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /
  def index
    @topics = Topic.page(params[:page])
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.create(topic_params)

    redirect_to action: :index
  end

  def show
    @topic = Topic.find(params[:id])
  end

  private
  def topic_params
    params.require(:topic).permit(:title, :body)
  end
end

app/controllers/uglyterms_controller.rb
class UglytermsController < ApplicationController
  before_action :set_uglyterm, only: [:show, :edit, :update, :destroy]

  # GET /uglyterms
  def index
    @uglyterms = Uglyterm.all
  end

  # GET /uglyterms/1
  def show
  end

  # GET /uglyterms/new
  def new
    @uglyterm = Uglyterm.new
  end

  # GET /uglyterms/1/edit
  def edit
  end

  # POST /uglyterms
  def create
    @uglyterm = Uglyterm.new(uglyterm_params)

    if @uglyterm.save
      redirect_to @uglyterm, notice: 'Uglyterm was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /uglyterms/1
  def update
    if @uglyterm.update(uglyterm_params)
      redirect_to @uglyterm, notice: 'Uglyterm was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /uglyterms/1
  def destroy
    @uglyterm.destroy
    redirect_to uglyterms_url, notice: 'Uglyterm was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_uglyterm
      @uglyterm = Uglyterm.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def uglyterm_params
      params.require(:uglyterm).permit(:term)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/uglyterms_helper.rb
module UglytermsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TalkDown</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <div class="container" id="stage">
      <%= yield %>
    </div>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/posts/_reply.html.erb
<%= simple_form_for Post.new, url: reply_post_path(post_id),  html: { class: "form-horizontal col-md-8" } do |f| %>
  <%= hidden_field_tag 'topic_id', topic_id %>
  <%= f.input :body, class: 'form-group' %>
  <%= f.submit 'Postar resposta', class: 'btn btn-default' %>
<% end %>

app/views/topics/_form.html.erb
<%= simple_form_for topic, html: { class: "form-vertical col-md-6 center-block" } do |f| %>
  <%= f.input :title, class: 'form-group' %>
  <%= f.input :body, as: :text %>

  <%= f.submit "Criar Tópico", class: 'btn btn-default' %>
<% end %>

app/views/topics/_list.html.erb
<ol>
  <% topics.each do |topic| %>
    <li><%= link_to topic.title, topic_path(topic) %></li>
  <% end %>
</ol>

<%= paginate topics %>

app/views/topics/_posts.html.erb
<ol>
  <% posts.each do |post| %>
    <li class='row'>
      <%= post.body %>
      <br />
      <%= render partial: post, locals: { post_id: post.id, topic_id: @topic.id } %>
      <br />
      <%= render partial: 'posts' , locals: { posts: post.replies } %>
    </li>
  <% end %>
</ol>

app/views/topics/_reply.html.erb
<%= simple_form_for Post.new, html: { class: "form-horizontal" }, remote: true do |f| %>
  <%= f.input :topic_id, as: :hidden, input_html: { value: topic_id } %>
  <%= f.input :body, input_html: { class: 'form-control' }, placeholder: 'Resposta', label: false %>
  <%= f.submit 'Postar', class: 'btn btn-default' %>
<% end %>

app/views/topics/_topics.html.erb
<ol>
<% topics.each do |topic| %>
  <li>
    <%= topic.title %>
    <%= render partial: 'posts', locals: { posts: topic.posts } %>
  </li>
<% end %>
</ol>

app/views/topics/index.html.erb
<h1>Topics</h1>

<div class='row'>
  <%= render partial: 'form', locals: { topic: Topic.new } %>
</div>
<hr />

<div class='row'>
  <%= render partial: 'list', locals: { topics: @topics } %>
</div>

app/views/topics/show.html.erb
<h1> Topic </h1>

<%= react_component 'Topic' %>
<hr />
<%= render partial: @topic, locals: { topic_id: @topic.id } %>
<hr />
<div class='row'
  <%= render partial: 'posts', locals: { posts: @topic.posts } %>
</div>

app/views/uglyterms/_form.html.erb
<%= simple_form_for(@uglyterm) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :term %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/uglyterms/edit.html.erb
<h1>Editing Uglyterm</h1>

<%= render 'form' %>

<%= link_to 'Show', @uglyterm %> |
<%= link_to 'Back', uglyterms_path %>

app/views/uglyterms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Uglyterms</h1>

<table>
  <thead>
    <tr>
      <th>Term</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @uglyterms.each do |uglyterm| %>
      <tr>
        <td><%= uglyterm.term %></td>
        <td><%= link_to 'Show', uglyterm %></td>
        <td><%= link_to 'Edit', edit_uglyterm_path(uglyterm) %></td>
        <td><%= link_to 'Destroy', uglyterm, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uglyterm', new_uglyterm_path %>

app/views/uglyterms/new.html.erb
<h1>New Uglyterm</h1>

<%= render 'form' %>

<%= link_to 'Back', uglyterms_path %>

app/views/uglyterms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Term:</strong>
  <%= @uglyterm.term %>
</p>

<%= link_to 'Edit', edit_uglyterm_path(@uglyterm) %> |
<%= link_to 'Back', uglyterms_path %>